-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-06-04 21:08:37 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--student id: 32312015
--student name: Syed Kabir
-- Capture run of script in file called mc_schema_output.txt
set echo on
SPOOL mc_schema_output.txt


DROP TABLE booking CASCADE CONSTRAINTS;

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE charge CASCADE CONSTRAINTS;

DROP TABLE cleaning CASCADE CONSTRAINTS;

DROP TABLE contract CASCADE CONSTRAINTS;

DROP TABLE contractor CASCADE CONSTRAINTS;

DROP TABLE guest CASCADE CONSTRAINTS;

DROP TABLE poi CASCADE CONSTRAINTS;

DROP TABLE poi_type CASCADE CONSTRAINTS;

DROP TABLE resort CASCADE CONSTRAINTS;

DROP TABLE review CASCADE CONSTRAINTS;

DROP TABLE town CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE booking (
    resort_id            NUMBER(7) NOT NULL,
    cbn_no               NUMBER(4) NOT NULL,
    guest_id             NUMBER(7) NOT NULL,
    bkg_checkin_date     DATE NOT NULL,
    "bkg-checkout_date"  DATE NOT NULL,
    bkg_total_charge     NUMBER(7, 2) NOT NULL,
    bkg_adult_no         NUMBER(2),
    bkg_child_no         NUMBER(2)
);

COMMENT ON COLUMN booking.resort_id IS
    'Resort identifier no';

COMMENT ON COLUMN booking.cbn_no IS
    'Cabin number';

COMMENT ON COLUMN booking.guest_id IS
    'Guest ID';

COMMENT ON COLUMN booking.bkg_checkin_date IS
    'Booking check- in date';

COMMENT ON COLUMN booking."bkg-checkout_date" IS
    'Booking check out date';

COMMENT ON COLUMN booking.bkg_total_charge IS
    'Booking total charge';

COMMENT ON COLUMN booking.bkg_adult_no IS
    'Booking adult numbers';

COMMENT ON COLUMN booking.bkg_child_no IS
    'Booking child numbers';

ALTER TABLE booking
    ADD CONSTRAINT booking_pk PRIMARY KEY ( cbn_no,
                                            resort_id,
                                            guest_id );

CREATE TABLE cabin (
    resort_id          NUMBER(7) NOT NULL,
    cbn_no             NUMBER(4) NOT NULL,
    cbn_bednumbers     NUMBER(2) NOT NULL,
    cbn_sleepcapacity  NUMBER(2) NOT NULL,
    cbn_description    VARCHAR2(100),
    cbn_std_cleantime  NUMBER(3) NOT NULL
);

COMMENT ON COLUMN cabin.resort_id IS
    'Resort identifier no';

COMMENT ON COLUMN cabin.cbn_no IS
    'Cabin number';

COMMENT ON COLUMN cabin.cbn_bednumbers IS
    'Cabin bed numbers';

COMMENT ON COLUMN cabin.cbn_sleepcapacity IS
    'Cabin sleep capacity';

COMMENT ON COLUMN cabin.cbn_description IS
    'Cabin description';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cbn_no,
                                                        resort_id );

CREATE TABLE charge (
    resort_id      NUMBER(7) NOT NULL,
    cbn_no         NUMBER(4) NOT NULL,
    ch_start_date  DATE NOT NULL,
    ch_cbnrate     NUMBER(7, 2),
    ch_end_date    DATE NOT NULL
);

COMMENT ON COLUMN charge.resort_id IS
    'Resort identifier no';

COMMENT ON COLUMN charge.cbn_no IS
    'Cabin number';

COMMENT ON COLUMN charge.ch_start_date IS
    'Charge rate start date';

COMMENT ON COLUMN charge.ch_cbnrate IS
    'Cabin charge rate';

COMMENT ON COLUMN charge.ch_end_date IS
    'Charge rate end date';

ALTER TABLE charge
    ADD CONSTRAINT charge_pk PRIMARY KEY ( ch_start_date,
                                           cbn_no,
                                           resort_id );

CREATE TABLE cleaning (
    resort_id             NUMBER(7) NOT NULL,
    cbn_no                NUMBER(4) NOT NULL,
    cleaning_datetime     DATE NOT NULL,
    cleaning_actual_time  NUMBER(3) NOT NULL,
    cleaning_charge       NUMBER(5, 2) NOT NULL,
    contractor_no         NUMBER(2) NOT NULL
);

COMMENT ON COLUMN cleaning.resort_id IS
    'Resort identifier no';

COMMENT ON COLUMN cleaning.cbn_no IS
    'Cabin number';

COMMENT ON COLUMN cleaning.cleaning_datetime IS
    'Cabin cleaning date and time';

COMMENT ON COLUMN cleaning.cleaning_actual_time IS
    'Cabin cleaning actual time';

COMMENT ON COLUMN cleaning.cleaning_charge IS
    'Cabin cleaning charge';

COMMENT ON COLUMN cleaning.contractor_no IS
    'Contractor No.';

ALTER TABLE cleaning
    ADD CONSTRAINT cabin_cleaning_pk PRIMARY KEY ( cleaning_datetime,
                                                   cbn_no,
                                                   resort_id );

CREATE TABLE contract (
    contractor_no     NUMBER(2) NOT NULL,
    contract_stdate   DATE NOT NULL,
    contract_enddate  DATE,
    contract_rate     NUMBER(4, 2) NOT NULL,
    contract_type     CHAR(1)
);

ALTER TABLE contract
    ADD CONSTRAINT ck_contract_type CHECK ( contract_type IN ( 'C', 'F' ) );

COMMENT ON COLUMN contract.contractor_no IS
    'Contractor No.';

COMMENT ON COLUMN contract.contract_stdate IS
    'Contract start date';

COMMENT ON COLUMN contract.contract_enddate IS
    'Contract end date';

COMMENT ON COLUMN contract.contract_rate IS
    'Contract hourly rate in dollar';

COMMENT ON COLUMN contract.contract_type IS
    'Contract type: C for casual; F for fixed';

ALTER TABLE contract ADD CONSTRAINT contractor_pk PRIMARY KEY ( contract_stdate,
                                                                contractor_no );

CREATE TABLE contractor (
    contractor_no         NUMBER(2) NOT NULL,
    contractor_fname      VARCHAR2(20) NOT NULL,
    contractor_lname      VARCHAR2(20) NOT NULL,
    contractor_address    VARCHAR2(200),
    contractor_phone      CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL,
    contractor_str_no     NUMBER(4),
    contractor_str_name   VARCHAR2(30),
    contractor_town_name  VARCHAR2(20),
    contractor_postcode   CHAR(4)
);

COMMENT ON COLUMN contractor.contractor_no IS
    'Contractor No.';

COMMENT ON COLUMN contractor.contractor_fname IS
    'Contractor first name';

COMMENT ON COLUMN contractor.contractor_lname IS
    'Contractor last name';

COMMENT ON COLUMN contractor.contractor_address IS
    'Contractor postal  address';

COMMENT ON COLUMN contractor.contractor_phone IS
    'Contractor phone number';

COMMENT ON COLUMN contractor.contractor_str_no IS
    'Contractor Address Street Number ';

COMMENT ON COLUMN contractor.contractor_str_name IS
    'Contractor address street name or GPO BOX including number';

COMMENT ON COLUMN contractor.contractor_town_name IS
    'Contractor address town name ';

COMMENT ON COLUMN contractor.contractor_postcode IS
    'Contractor address postcode';

ALTER TABLE contractor ADD CONSTRAINT contractor_pkv2 PRIMARY KEY ( contractor_no );

CREATE TABLE guest (
    guest_id                NUMBER(7) NOT NULL,
    guest_fname             VARCHAR2(20) NOT NULL,
    guest_lname             VARCHAR2(20) NOT NULL,
    guest_address_stno      VARCHAR2(4),
    guest_address_stname    VARCHAR2(20),
    guest_address_townname  VARCHAR2(20),
    guest_address_postcode  CHAR(4),
    guest_email             VARCHAR2(20),
    guest_phoneno           VARCHAR2(12) NOT NULL
);

COMMENT ON COLUMN guest.guest_id IS
    'Guest ID';

COMMENT ON COLUMN guest.guest_fname IS
    'Guest first name';

COMMENT ON COLUMN guest.guest_lname IS
    'Guest last name';

COMMENT ON COLUMN guest.guest_address_stno IS
    'Guest address street number';

COMMENT ON COLUMN guest.guest_address_stname IS
    'Guest address street name';

COMMENT ON COLUMN guest.guest_address_townname IS
    'Guest address town name';

COMMENT ON COLUMN guest.guest_address_postcode IS
    'Guest Address post code';

COMMENT ON COLUMN guest.guest_email IS
    'Guest email address';

COMMENT ON COLUMN guest.guest_phoneno IS
    'Guest phone number';

ALTER TABLE guest ADD CONSTRAINT guest_pk PRIMARY KEY ( guest_id );

CREATE TABLE poi (
    poi_id           NUMBER(7) NOT NULL,
    poi_streetname   VARCHAR2(30) NOT NULL,
    poi_name         VARCHAR2(20) NOT NULL,
    tn_latitude      NUMBER(8, 6) NOT NULL,
    tn_longitude     NUMBER(9, 6) NOT NULL,
    poi_opentime     DATE NOT NULL,
    poi_closetime    DATE NOT NULL,
    poi_description  VARCHAR2(100),
    poi_type_id      NUMBER(5) NOT NULL
);

COMMENT ON COLUMN poi.poi_id IS
    'POI ID';

COMMENT ON COLUMN poi.poi_streetname IS
    'POI Street name';

COMMENT ON COLUMN poi.poi_name IS
    'POI name';

COMMENT ON COLUMN poi.tn_latitude IS
    'Town location latitude';

COMMENT ON COLUMN poi.tn_longitude IS
    'Town location langitude';

COMMENT ON COLUMN poi.poi_opentime IS
    'POI  opening time';

COMMENT ON COLUMN poi.poi_closetime IS
    'POI closing time';

COMMENT ON COLUMN poi.poi_description IS
    'POI Description';

ALTER TABLE poi ADD CONSTRAINT poi_pk PRIMARY KEY ( poi_id );

ALTER TABLE poi
    ADD CONSTRAINT poi_nk UNIQUE ( poi_streetname,
                                   poi_name,
                                   tn_latitude,
                                   tn_longitude );

CREATE TABLE poi_type (
    poi_type_id  NUMBER(5) NOT NULL,
    poi_type     VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN poi_type.poi_type IS
    'POI Type';

ALTER TABLE poi_type ADD CONSTRAINT poi_type_pk PRIMARY KEY ( poi_type_id );

CREATE TABLE resort (
    resort_id           NUMBER(7) NOT NULL,
    resort_name         VARCHAR2(20) NOT NULL,
    resort_streetno     VARCHAR2(4) NOT NULL,
    resort_streetname   VARCHAR2(30) NOT NULL,
    resort_town         VARCHAR2(30) NOT NULL,
    resort_postcode     CHAR(4) NOT NULL,
    resort_contactno    CHAR(10),
    resort_pet_allowed  CHAR(1 CHAR) NOT NULL,
    resort_star_rating  CHAR(1) NOT NULL,
    tn_latitude         NUMBER(8, 6) NOT NULL,
    tn_longitude        NUMBER(9, 6) NOT NULL
);

ALTER TABLE resort
    ADD CONSTRAINT chk_petallowed CHECK ( resort_pet_allowed IN ( 'N', 'Y' ) );

ALTER TABLE resort
    ADD CONSTRAINT chk_rating CHECK ( resort_star_rating BETWEEN '1' AND '5' );

COMMENT ON COLUMN resort.resort_id IS
    'Resort identifier no';

COMMENT ON COLUMN resort.resort_name IS
    'Resort name';

COMMENT ON COLUMN resort.resort_streetno IS
    'Resort adress street number';

COMMENT ON COLUMN resort.resort_streetname IS
    'Resort address street name';

COMMENT ON COLUMN resort.resort_town IS
    'Resort address town';

COMMENT ON COLUMN resort.resort_postcode IS
    'Resort address post code';

COMMENT ON COLUMN resort.resort_pet_allowed IS
    'Do resort allow pet? Y or N';

COMMENT ON COLUMN resort.resort_star_rating IS
    'star rating of resort. 1= lowest; 5= Highest';

COMMENT ON COLUMN resort.tn_latitude IS
    'Town location latitude';

COMMENT ON COLUMN resort.tn_longitude IS
    'Town location langitude';

ALTER TABLE resort ADD CONSTRAINT resort_pk PRIMARY KEY ( resort_id );

CREATE TABLE review (
    resort_id       NUMBER(7) NOT NULL,
    guest_id        NUMBER(7) NOT NULL,
    review_date     DATE NOT NULL,
    review_rating   NUMBER NOT NULL,
    review_comment  VARCHAR2(200)
);

COMMENT ON COLUMN review.resort_id IS
    'Resort identifier no';

COMMENT ON COLUMN review.guest_id IS
    'Guest ID';

COMMENT ON COLUMN review.review_date IS
    'Review date';

COMMENT ON COLUMN review.review_rating IS
    'Review rating.';

COMMENT ON COLUMN review.review_comment IS
    'Review comment';

ALTER TABLE review ADD CONSTRAINT review_pk PRIMARY KEY ( resort_id,
                                                          guest_id );

CREATE TABLE town (
    tn_latitude    NUMBER(8, 6) NOT NULL,
    tn_longitude   NUMBER(9, 6) NOT NULL,
    tn_name        VARCHAR2(20) NOT NULL,
    tn_state       VARCHAR2(20),
    tn_sum_temp    NUMBER(2),
    tn_wint_temp   NUMBER(2),
    tn_population  NUMBER(10)
);

COMMENT ON COLUMN town.tn_latitude IS
    'Town location latitude';

COMMENT ON COLUMN town.tn_longitude IS
    'Town location langitude';

COMMENT ON COLUMN town.tn_name IS
    'Town name';

COMMENT ON COLUMN town.tn_state IS
    'Town state name';

COMMENT ON COLUMN town.tn_sum_temp IS
    'Town average summer temperature in centigrade';

COMMENT ON COLUMN town.tn_wint_temp IS
    'Town average winter temperature in centigrade';

COMMENT ON COLUMN town.tn_population IS
    'Town population';

ALTER TABLE town ADD CONSTRAINT town_pk PRIMARY KEY ( tn_latitude,
                                                      tn_longitude );

ALTER TABLE booking
    ADD CONSTRAINT cabin_booking FOREIGN KEY ( cbn_no,
                                               resort_id )
        REFERENCES cabin ( cbn_no,
                           resort_id );

ALTER TABLE cleaning
    ADD CONSTRAINT cabin_cabin_cleaning FOREIGN KEY ( cbn_no,
                                                      resort_id )
        REFERENCES cabin ( cbn_no,
                           resort_id );

ALTER TABLE charge
    ADD CONSTRAINT cabin_charge FOREIGN KEY ( cbn_no,
                                              resort_id )
        REFERENCES cabin ( cbn_no,
                           resort_id );

ALTER TABLE cleaning
    ADD CONSTRAINT cleaning_contractor FOREIGN KEY ( contractor_no )
        REFERENCES contractor ( contractor_no );

ALTER TABLE contract
    ADD CONSTRAINT contractor_contract FOREIGN KEY ( contractor_no )
        REFERENCES contractor ( contractor_no );

ALTER TABLE booking
    ADD CONSTRAINT guest_booking FOREIGN KEY ( guest_id )
        REFERENCES guest ( guest_id );

ALTER TABLE review
    ADD CONSTRAINT guest_review FOREIGN KEY ( guest_id )
        REFERENCES guest ( guest_id );

ALTER TABLE poi
    ADD CONSTRAINT poi_type_poi FOREIGN KEY ( poi_type_id )
        REFERENCES poi_type ( poi_type_id );

ALTER TABLE cabin
    ADD CONSTRAINT resort_cabin FOREIGN KEY ( resort_id )
        REFERENCES resort ( resort_id );

ALTER TABLE review
    ADD CONSTRAINT resort_review FOREIGN KEY ( resort_id )
        REFERENCES resort ( resort_id );

ALTER TABLE poi
    ADD CONSTRAINT town_poi FOREIGN KEY ( tn_latitude,
                                          tn_longitude )
        REFERENCES town ( tn_latitude,
                          tn_longitude );

ALTER TABLE resort
    ADD CONSTRAINT town_resort FOREIGN KEY ( tn_latitude,
                                             tn_longitude )
        REFERENCES town ( tn_latitude,
                          tn_longitude );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 1

SPOOL off
set echo off